# WINDOW CONFIGURATION
WIDTH = 1200
HEIGHT = 600
WINDOW_TITLE = "AQUARIUM"

# BOIDS CONFIGURATION
NUM_BOIDS = 200
MAX_SPEED = 3.0
NEIGHBOR_RADIUS = 80
MAX_FORCE = 0.2

# PHYSICS SETTINGS
BOID_FRICTION = 0.01
WANDER_STRENGTH = 0.3

# BEHAVIOR FACTORS
SEPARATION_FACTOR = 2.0
ALIGNMENT_FACTOR = 1.2
COHESION_FACTOR = 1.0